require("./common/module/dotenv")()
const express = require("express")
const app = express()
const path = require("path")
const cors = require("cors")
const notFoundRouter = require("./common/error/not-found-mw")
const errorRouter = require("./common/error/error-mw")
app.listen(process.env.port)
app.set("view engine", "ejs")
app.set("views", path.resolve(__dirname, "./views"))
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({ extended: false }))
app.use("/", express.static("./public"))

const shopRouter = require("./routes/shop-router")
const bookRouter = require("./routes/book-router")
const publicRouter = require("./routes/public-router")

app.use("/shop", shopRouter)
app.use("/book", bookRouter)
app.use("/public", publicRouter)

app.use(notFoundRouter)
app.use(errorRouter)
