/* 라우터 분리 */
require("./modules/dotenv")()
const express = require("express")
const app = express()
const path = require("path")
const mw01 = require("./middlewares/mw01")
const mw02 = require("./middlewares/mw02")
app.listen(process.env.port)
app.set("view engine", "ejs")
app.set("views", path.resolve(__dirname, "./views"))
app.use(express.json())
app.use(express.urlencoded({ extended: false }))
app.use("/", express.static("./public"))
